version: '3.8'
services:
  app:
    build: .
    volumes:
      - learnclivolume:/playground
    stdin_open: true
    tty: true
    command: /learncli/env/bin/python /learncli/main.py

volumes:
  learnclivolume: