version: '3'
services:
  app:
    build: .
    volumes:
      - .:/learncli
      - /learncli/env
    stdin_open: true
    tty: true
    ports:
      - "4000:4000"
    command: /learncli/env/bin/python /learncli/main.py